### ISSUE TITLE
Example doesn't work in create-react-app

### ISSUE THREAD

**Issue by inancgumus** [drcmda/react-springy-parallax#1]
There's an error when I try to run the example in a default create-react-app. This may be due because of create-react-app, I didn't try it yet. However, so many people are using create-react-app and I thought that it might be fixed.

# Error:

_Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)._

# Reproduce:

### Installation

```bash
create-react-app example2
cd example2

npm i react-springy-parallax -S

# edit App.js
# to add code from your example/index.js (like below)

npm start
```

### create-react-app App.js

```javascript
import React, { Component } from 'react';
import './App.css';

import Parallax from 'react-springy-parallax';

const styles = {
  fontFamily: 'Menlo-Regular, Menlo, monospace',
  fontSize: 14,
  lineHeight: '10px',
  color: 'white',
  display: 'flex', alignItems: 'center', justifyContent: 'center'
}

class App extends Component {
  render() {
    return (
      <div className="App">
        <Parallax ref="parallax" pages={3}>

          <Parallax.Layer offset={0} speed={1} style={{ backgroundColor: '#243B4A' }} />
          <Parallax.Layer offset={1} speed={1} style={{ backgroundColor: '#805E73' }} />
          <Parallax.Layer offset={2} speed={1} style={{ backgroundColor: '#87BCDE' }} />

          <Parallax.Layer
            offset={0}
            speed={0.5}
            style={styles}
            onClick={() => this.refs.parallax.scrollTo(1)}>
            Click!>
          </Parallax.Layer>

          <Parallax.Layer
            offset={1}
            speed={-0.1}
            style={styles}
            onClick={() => this.refs.parallax.scrollTo(2)}>
            Another page ...
          </Parallax.Layer>

          <Parallax.Layer
            offset={2}
            speed={0.5}
            style={styles}
            onClick={() => this.refs.parallax.scrollTo(0)}>
            The end.
          </Parallax.Layer>

        </Parallax>
      </div>
    );
  }
}

export default App;
```

**Comment by drcmda** [comment]
Hi @inancgumus 

I think you may have tried with an older version, i've since removed refs altogether as it was a little hacky anyway. I tried with create-react-app and simply dropped the code into /src/App.js and it worked. Though i had to npm install `animated` as it wasn't in the dependencies. Theoretically that should be fixed as well with the latest 1.0.5.

I would be glad if you could update, try again and write back.

**Comment by inancgumus** [comment]
Hi @drcmda 

Yeah, you're right, thx! I was using `create-react-app` with version 0.6.0. I updated it and it works now. It also installed `animated@0.2.0` together with `react-springy-parallax` package.

```
live@0.1.0 /Users/inanc/dev/react-springy-parallax/live
└─┬ react-springy-parallax@1.0.5
  └─┬ animated@0.2.0
    └── normalize-css-color@1.0.2
```

**Comment by drcmda** [comment]
Awesome, thanks for letting me know!

**Comment by inancgumus** [comment]
Sure thing!
