### ISSUE TITLE
Server rendering :-/

### ISSUE THREAD

**Issue by nesvet** [drcmda/react-springy-parallax#13]
Layers content completely disappears being rendered on a server :-( It comes to a client as an empty div. Next, on a client everything is fine.

Is there any way to let search engines to index layers content?

**Comment by drcmda** [comment]
@Nesvet i don't have much experience with server rendering, never actually tried it. Would you submit a PR? Or do you know any obvious changes i would have to make to support it?

**Comment by nesvet** [comment]
Hi, @drcmda, yes, the problem is in `render()` method:
It check's `this.state.ready` before it will render `"content"` and `{children}`. Since server code runs synchronously (right?) `this.state.ready` is always `false` and we never see `{children}`. I was able to make this work by doing
```jsx
class ParallaxFixed extends Parallax {
	constructor(props) {
		super(props);
		this.state = {ready: true};
	}
}
```

Everything looks working fine. Is `this.state.ready` check really needed?

**Comment by drcmda** [comment]
@Nesvet It had something to do with getting the correct height from the content container after the mount, then fill in the children with the calculated pages heights. I'm actually stunned that you say it works without, it ... shouldn't. Though the `state.ready` solution for sure was a dirty workaround.
