### ISSUE TITLE
Source for demo?

### ISSUE THREAD

**Issue by brianbolnick** [drcmda/react-springy-parallax#15]
Is this available to see anywhere? Trying to understand how to use multi-layers. That would be great if so :)

**Comment by sergiofruto** [comment]
I came here to ask the same thing! 
The docs are great explaining how the multiple page Parallax works, but I need more details regarding several elements scrolling at different speed in the same page, or multi-layers. 
The bottom of the demo page (image attached) is pretty close to what I need, so if you could upload the source code for the Demo, that would be great! 

Thanks a lot and great job! 

![image](https://user-images.githubusercontent.com/4473420/31688548-0bc74e84-b363-11e7-842e-6fc5980c71e8.png)

**Comment by Juanelorganelo** [comment]
Found it, it's in [another repo](https://github.com/drcmda/awv3node-homepage/blob/master/components/App.js)

**Comment by drcmda** [comment]
I added it to the frontpage.
