### ISSUE TITLE
Suggestions for Responsive/Mobile

### ISSUE THREAD

**Issue by insipx** [drcmda/react-springy-parallax#16]
Hey,

Using react-springy-parallax works great most of the time on desktop. However, on mobile much of the content in the parallax is cutoff. Any suggestions for using this on mobile?

**Comment by drcmda** [comment]
@InsidiousMind it should scale to 100vh, which shouldn't be cut off. I had this little demo, it ran fine on the phones i tested it on. Do you have more specific advice?
