### ISSUE TITLE
Module not found: Error: Can't resolve 'react-dom/lib/CSSPropertyOperations'

### ISSUE THREAD

**Issue by drjuarez** [drcmda/react-springy-parallax#17]
ERROR in ./node_modules/animated/lib/targets/react-dom.js
Module not found: Error: Can't resolve 'react-dom/lib/CSSPropertyOperations'

react-spring-parallax: 1.1.0
react: 16.0.0
react-dom: 16.0.0

I appreciate your work on the package and any insight you can give me.

Thanks!

**Comment by brianbolnick** [comment]
I believe this has something to do with the animated library not being compatible with React v16.

**Comment by drjuarez** [comment]
@brianbolnick Thanks for your response.  Looks like there was a commit that added react 16 compatibility.  So don't think it'd be that.

**Comment by mgreer** [comment]
I think with React 16 you need only-react-css-property-operations. React 16 seals off those internal libraries.
So... you are not using the latest commit.

**Comment by drcmda** [comment]
@drjuarez Have you figured it out? I did merge a wrap around animated (react-dom-animated) to make it work on r16.

**Comment by drcmda** [comment]
animated 0.2.1 just came out, this should fix most problems. The lib from this point on will depend on React 16.
