### ISSUE TITLE
Anyone wants to help maintaining, taking control?

### ISSUE THREAD

**Issue by drcmda** [drcmda/react-springy-parallax#18]
I would love to extend this, check in on the issues, etc. But my job is keeping me too busy often. I would be glad to share the rights to this.

**Comment by FreakDroid** [comment]
@drcmda Heya, currently I was checking your Library and it's awesome. I don't exactly what are you looking for the people to keep this lib updated? only permission to accept PR? or also should code and help???

**Comment by drcmda** [comment]
@FreakDroid updates, extensions, new ideas, tests, etc. All welcome 😀

**Comment by FreakDroid** [comment]
@drcmda I could try, but honestly I feel pretty newbie with react (Although I've experience) Let me check first how I can help, and after I'll decide whether I've skill to everything that you said or not. 😄 

Do you have, any todo list for this project???

**Comment by ghost** [comment]
Would also like to help contribute!

**Comment by drcmda** [comment]
@healingfromjava @FreakDroid Until now testing, maybe horizontal scrolling would also be nice. PRs welcome and i'd add you to the project.

**Comment by FreakDroid** [comment]
@drcmda I think this weekend I can start with checking the test :+1:  And I agree with you about horizontal scrolling, It's necessary.

**Comment by drcmda** [comment]
@FreakDroid sure, would be awesome, if you find time i'd be glad to accept PRs, maintenance, etc.
