### ISSUE TITLE
Does this work horizontally?

### ISSUE THREAD

**Issue by ChCosmin** [drcmda/react-springy-parallax#19]
Can the parallaxes be set to be side by side and to be moved from left to right(& viceversa) on clicks(/ horizontal scroll)?

**Comment by drcmda** [comment]
@ChCosmin not really, but would be easy to do. Do you want to make a PR?

**Comment by brianbolnick** [comment]
Would love this too!

**Comment by drcmda** [comment]
@ChCosmin @brianbolnick Not yet, but would be easy to implement. Any of you up for a PR? would basically consist of a new prop (horizontal={true/false}) and some minor tweaks elsewhere.

**Comment by drcmda** [comment]
@ChCosmin @brianbolnick Just added it today, just pass `horizontal` to the Parallax component and it should work. 😀

**Comment by drcmda** [comment]
![kapture 2018-03-21 at 23 51 45](https://user-images.githubusercontent.com/2223602/37742109-7ecca4ee-2d64-11e8-9bde-b4426e595722.gif)

**Comment by FreakDroid** [comment]
Awesome @drcmda

**Comment by drcmda** [comment]
Thanks a lot @FreakDroid 

I merged this into react-spring (https://github.com/drcmda/react-spring) today, if you haven't, check it out - from now on i'll focus more on that lib as it's far more complete. It also has the code for the demo above: https://codesandbox.io/embed/548lqnmk6l
