### ISSUE TITLE
Works great with touchpad, very jerky with mouse wheel

### ISSUE THREAD

**Issue by cpsubrian** [drcmda/react-springy-parallax#2]
The effect looks really great when using the touchpad or grabbing the scrollbar with my mouse, but when I scroll with a mouse wheel the parallax is very jerky.

**Comment by inancgumus** [comment]
It works greats with me (_works on my machine syndrome?!_). OS X Sierra + iMac.

**Comment by cpsubrian** [comment]
Yeah I suspect it's very hardware/setting dependent. FWIW I'm on El Capitan / MacbookPro / Razer Mouse.

**Comment by drcmda** [comment]
@cpsubrian yep, i have a windows mouse here that scrolls in what feels like "chunks" on my mac and the parallax fight against it as it basically bounces every chunk. Not just this parallax, all of them look bad though. I could switch spring to a timed animation that would allow for a small delay and then shift things into place. I tried this already and it looks way better (with that particular mouse) but no idea how i'd detect a chunky mouse to make the switch. : /

I'll start anyway making the effect configurable.

**Comment by cpsubrian** [comment]
@drcmda Glad I'm not crazy :smile: I agree that detecting these types of device differences is difficult. Just wanted to record my experience in case you were curious.

**Comment by drcmda** [comment]
@cpsubrian could you npm update and try something like this:

```js
import Animated from 'animated/lib/targets/react-dom'

<Parallax
    effect={(animation, toValue) => 
        Animated.timing(animation, { toValue, duration: 200 })}
    ...
```

This lets you control the animation driver. A time based animation gives the parallax some room. You can use anything the Animated library offers: http://browniefed.com/react-native-animation-book If you add an easing for instance you can even get the bouncing back. 

```js
import Easing from 'animated/lib/Easing'
effect={(animation, toValue) => 
    Animated.timing(animation, { toValue, duration: 200, easing: Easing.elastic(2) })}
```

If nothing helps, a zero timed animation will kill the effect but at least give you a standard parallax:

    Animated.timing(animation, { toValue, duration: 0 })
