### ISSUE TITLE
How the animation could be edited and controlled?

### ISSUE THREAD

**Issue by 01Kuzma** [drcmda/react-springy-parallax#20]
Hi!
Could you please explain more about how to use animation with you library?
In you sample:
```
<img
     src={url('server')}
     style={{ width: '20%', transform: [{ scale: this.animation }] }}
   />
```

is `this.animation` pre-difined value?
How different animations could be used? such as bounce-in, rotation, spin?
I've tried this:
```
style={{
          transform: [{rotate: spin}] }}
```
But `spin` is undefined.

Thank you very much
P.S. I've glanced at http://browniefed.com/react-native-animation-book/ but it looks like more advanced examples

**Comment by drcmda** [comment]
@01Kuzma hi there! 

You mean like how to use animated generally? I've made an easy to grasp example a while ago: https://www.webpackbin.com/bins/-KfKys3S2mgEH9UsE8GL

animated basically allows you pass "animatable values", something which is normal in react-native but unfortunately not in react-dom. So with this you can drive animations from outside. Play a little with the example if you like and if you have questions, just write back.

**Comment by 01Kuzma** [comment]
Thank you very much!
I will take a look!
By the way the `this.animation` from `App.js`
```
    style={{ width: '20%', transform: [{ scale: this.animation }] }}
```
does carry any pre-defined values or properties?

P.S. the https://www.webpackbin.com/bins/-KfKys3S2mgEH9UsE8GL throws a error: `Sorry, something went wrong, please report or refresh`

**Comment by drcmda** [comment]
@01Kuzma sorry, webpackbin seems to have an outage, here's the same on codesandbox:

https://codesandbox.io/s/7j3m2v9j7x

**Comment by 01Kuzma** [comment]
Great, thank you!

**Comment by 01Kuzma** [comment]
Could you please provide example, how the multiple items could be animated inside different Parallax layers?

As from example:
```
...
                <Parallax.Layer                
                    offset={0} speed={0.5}
                    style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                    onClick={() => this.parallax.scrollTo(1)}>
                    <img
                        src={url_assets_foundation('01-foundation')}
                        style={{ width: '20%', transform: [{ scale: this.animation }] }}
                    />                    
                    <div
                        style={{
                            whiteSpace: 'pre',
                            fontFamily: 'Menlo-Regular, Menlo, monospace',
                            fontSize: 14,
                            lineHeight: '10px',
                            color: 'white'
                        }}>
                        <p><Gray> &gt;</Gray>  npm install awv3-node --save</p>
                        <br />
                        <p><Gray> 1</Gray>  <Pink>const</Pink> Server <Pink>=</Pink> <Lightblue>require</Lightblue><Gray>(</Gray><Green>'awv3-node/server'</Green><Gray>)</Gray></p>
                        <br />
                        <p><Gray> 2</Gray>  <Pink>new</Pink> Server<Gray>(&#123;</Gray></p>
                        <p><Gray> 3</Gray>      <Yellow>output</Yellow><Pink>:</Pink> __dirname <Pink>+</Pink></p>
                        <p>            <Green>'/node_modules/@awv/classcad_cadapplication'</Green><Gray>,</Gray></p>
                        <p><Gray> 4</Gray>      <Yellow>config</Yellow><Pink>:</Pink> <Green>'CADApplication.ini'</Green><Gray>,</Gray></p>
                        <p><Gray> 5</Gray>      <Yellow>publicport</Yellow><Pink>:</Pink> <Blue>process</Blue>.<Blue>env</Blue>.<Blue>port</Blue> <Pink>||</Pink>&nbsp;8181<Gray>,</Gray></p>
                        <p><Gray> 6</Gray>      <Yellow>privateport</Yellow><Pink>:</Pink> 9191<Gray>,</Gray></p>
                        <p><Gray> 7</Gray>      <Yellow>instances</Yellow><Pink>:</Pink> 3</p>
                        <p><Gray> 8</Gray>  <Gray>})</Gray><Pink>.</Pink><Lightblue>start</Lightblue><Gray>()</Gray></p>
                    </div>
                </Parallax.Layer>

                <Parallax.Layer
                    offset={1} speed={0}
                    onClick={() => this.parallax.scrollTo(2)}
                    style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <img
                        src={url('server')}
                        style={{ width: '20%', transform: [{ scale: this.animation }] }}
                    />
                </Parallax.Layer>
...
```

could the text from the first layer and image from the second be separately animated?

**Comment by drcmda** [comment]
@01Kuzma everything that happens within these layers is basically up to you, react-parallax will just shift the stuff around on scrolling. Inside of course you can use animated or react-motion or anything you like to animate contents separately.

If you want to keep using animated make sure to use it correctly, you can't put this.animation (an animatable value i suppose) into a regular react style. `Animated.div`, `Animated.span` and `Animated.img` extend styles so that it is possible.

I'd suggest playing around with that codesandbox some more, try to get an image animating. Then read some more docs on how to use animated, there's a lot of things it can do.
