### ISSUE TITLE
Once any link from page is clicked - the scroll is engaded

### ISSUE THREAD

**Issue by 01Kuzma** [drcmda/react-springy-parallax#21]
Hi!
I've found one specific issue. 
Once any added to parallax layer link is clicked - the scroll to next layer is engaged.  Right now I'm implementing modal-dialog which is accessed through links. So app behaves in such way: 

- click on link
- the layer shifts and background colour is shown (related to fist page) | the layer is shifted to next one(non first layer)
- modal is shown, but the page is reloads! Seems that this behaviour related also to first slide

How could it be fixed? Could the behaviour of internal links changed to ignore scroll action?

**Comment by drcmda** [comment]
@01Kuzma Do you have an example some where, codesandbox would be great. It shouldn't scroll at all, unless you call `scrollTo`.

**Comment by 01Kuzma** [comment]
I'm doing it locally... Yes, I've set the `scrolling={true}`  and `onClick={() => this.parallax.scrollTo(X)}` is laso used, what is very nice. But in conjunction of both options any clicked link, such as `a href="#">Test</a>`, will do it's task and layer will scroll to next. So in such way it's impossible to have `scrollTo` enabled and links for UI...

**Comment by drcmda** [comment]
I think i get it now, but it seems to me that's normal dom behavior. If you set the click event on the parent-parallax section, then clicks on underlying elements will bubble up and eventuell reach the parallaxes click handler. You can prevent events from doing that using `event.stopPropagation()`.

**Comment by 01Kuzma** [comment]
And how and where the `event.stopPropagation` should be used?

**Comment by drcmda** [comment]
Something like this i guess ...

```js
class Something extends Component {
    stopPropagation = e => e.stopPropagation()
    ...
    <a href="#" onClick={this.stopPropagation}>Test</a>
}
```

Live demo: https://codesandbox.io/s/48l006mvn0

The problem isn't springy-parallax, it's the doms regular event distribution that's playing a trick. The event just bubbles up as i suspected, reaching the parallax handler and there it scrolls. If you prevent the event from doing that it'll be fine. Alternatively don't put the onClick handler on the parallax parent but something underneath the link.

**Comment by 01Kuzma** [comment]
Thank you very much!!!
It seems to work :)
