### ISSUE TITLE
'Using this.refs is deprecated. (react/no-string-refs)' source: 'eslint'

### ISSUE THREAD

**Issue by spences10** [drcmda/react-springy-parallax#3]
Hi, love this, I'm just getting started out with react and I'm not sure how to use `this` with `this.refs.parallax.scrollTo` 

Do I need to add it into the constructor?
![image](https://cloud.githubusercontent.com/assets/234708/24373161/5eaebfa0-1328-11e7-8f77-0deb01860205.png)

I have just used the example code with some light editing

So, how do I use it?

Do I need to do it with a stateless function?

Thanks again

**Comment by spences10** [comment]
What I'm wanting to achieve is navigation on the page via nav clicks

So if I use something like:

```
<Nav 
  about='about-link'
  portfolio='portfolio-link'
  contact='contact-link' 
/> 
```

Then in the nav component use `scrollTo` somehow?

Apologies if it seems that I'm not totally clear on what I need to do, that's because I'm learning as I go along 🙃

**Comment by spences10** [comment]
I haven't tried yet but I'm guessing I may need to use a named export or use `react-router` 

I'm thinking if i use react router it's just going to show the one component so there may be no parallax effect there so I'll try using the named export first

Something like: 

Nav.js:
```
import { scrollTo } from 'react-springy-parallax'
```

**Comment by spences10** [comment]
So trying to use a named export, from here:

![image](https://cloud.githubusercontent.com/assets/234708/24398816/c03bc612-13a2-11e7-9010-2160e6dac19e.png)

And using in my code here:

![image](https://cloud.githubusercontent.com/assets/234708/24398875/e116b64e-13a2-11e7-8a48-a881001d4df3.png)

I get an error saying that `scrollTo` is not a function??

![image](https://cloud.githubusercontent.com/assets/234708/24398923/05e1034e-13a3-11e7-890c-ce248298234b.png)

Do I need to reference it a different way?

**Comment by drcmda** [comment]
@spences10 You either use a named ref, `<Pararallax ref="parallax" ...` and now within the containing class you can do `this.refs.parallax` and you'll get the instance of Parallax, which features the `scrollTo`function. 

If your linter complains about it, use functional refs, which are encouraged by React i guess, it's all the same:

```js
render() {
    return (
        <Parallax
            ref={ref => this.parallax = ref}
            ... >
            <something onClick={() => this.parallax.scrollTo(1)}
```

You later try to get scrollTo with `nav`, that's not gonna work. Nav is just a HTML element, it doesn't have that kind of functionality. Your top-most element should be Parallax, then Parallax.Layer(s). Now you can scroll to any page you want.

You can read more about React refs here: https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by drcmda** [comment]
PS. here's a real world example:

demo: http://awv3node-homepage.surge.sh/
source: https://github.com/drcmda/awv3node-homepage/blob/master/components/App.js

**Comment by spences10** [comment]
Ok, linting resolved with `ref={ref => (this.parallax = ref)}` which is a workaround but it's still an assignment

I tried to pass the `scrollTo` to a different component so I could call it from there as a function, so I did:

```
class App extends React.Component {
  constructor(props) {
    super(props)
    this.handleScroll = value => this.parallax && this.parallax.scrollTo(value)
  }
  render() {
    return (
      <div>
        <Parallax
          ref={ref => (this.parallax = ref)}
          pages={4}
        >
```

Then passed it into to component:

```
          <Parallax.Layer
            offset={0}
            speed={0.5}
            onClick={() => this.handleScroll(1)}
          >
            <Nav handleScroll={this.handleScroll} />
```

Then I was trying to call it from that component in an `<a href="#" onClick={this.props.handleScroll}...` which sort of worked but it triggered the event on each of the links when it was rendered, even then clicking the links still just scrolled to the next page

I could trigger `handleScroll` from the react dev tool and jump to the correct page there by passing the desired page number

It's clear I still have a lot to learn here

Thanks for your comments @drcmda

**Comment by drcmda** [comment]
@spences10 That would work, you can pass the function down. But when you get the onClick in your `<a href="#"` then you must call it with the page you need: `onClick={() => this.props.handleScroll(PAGE)}`.

**Comment by spences10** [comment]
Hey @drcmda where has your note on using `contextTypes` gone?

There was some handy references on here too 😞 

So I have used:

```
Nav.contextTypes = { parallax: React.PropTypes.object }
```

So I can then access the `scrollTo` method in the `Nav` component, this thing is that when the page loads it appears that all the `onClick` events are happening 

Here is the `Nav` component 

```
class Nav extends React.Component {
  render() {
    return (
      <div className="nav">
        <ul className="links">
          <li>
            <a
              href=""
              onClick={this.context.parallax.scrollTo(0)}
            >
              Home
            </a>
          </li>
          <li>
            <a
              href=""
              onClick={this.context.parallax.scrollTo(1)}
            >
              About
            </a>
          </li>
```

There's another two links and when the page loads up it will got to the last page comment out the last link and it goes to the second to last page

**Comment by drcmda** [comment]
@spences10  I figured it's too implicit, but that's how it works internally, layers know Parallax through context. But if it works for you then that's alright. The reference was from Reacts docs: https://facebook.github.io/react/docs/context.html

**Comment by spences10** [comment]
Thanks for all your help @drcmda, I'll close this as it's more of a learning point for me rather than an issue with the repo

I've removed the click handlers and the whole nav now as using `contextTypes` seemed to slow down the pages to the point of them being unresponsive.

Just going to go with 'click through' for now until I'm  ore knowledgeable on the subject 🙃 

Thanks again 👍
