### ISSUE TITLE
Parallax.Layer doesn't have className property

### ISSUE THREAD

**Issue by oiojin831** [drcmda/react-springy-parallax#4]
I can't use className in Parallax.layer.
I guess this is because it doesn't have className property.
Please let me know if I am wrong.

Thanks

**Comment by drcmda** [comment]
@oiojin831 How odd, should have worked. I made it explicit now (1.0.8) just to be sure. npm update and it should work.

**Comment by oiojin831** [comment]
@drcmda Thanks for the fast response!!
I guess the problem wasn't from this project.
It seems the element has the class but the style wasn't applied. I am using styled-jsx btw.
Thanks, I will close the issue.
